# pylint: disable=protected-access
# pylint: disable=line-too-long
# These are automatically generated files and many pylint issues are expected
# DO NOT EDIT!

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x1a\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1d\n\rAudioResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"-\n\nImageFrame\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\t\"$\n\rImageResponse\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\"\x1e\n\x0eMessageRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"0\n\x0fMessageResponse\x12\r\n\x05reply\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t2\x96\x01\n\x08PiServer\x12.\n\x0bStreamAudio\x12\x0b.AudioChunk\x1a\x0e.AudioResponse(\x01\x30\x01\x12(\n\tSendImage\x12\x0b.ImageFrame\x1a\x0e.ImageResponse\x12\x30\n\x0bSendMessage\x12\x0f.MessageRequest\x1a\x10.MessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_AUDIOCHUNK']._serialized_start=17
    _globals['_AUDIOCHUNK']._serialized_end=43
    _globals['_AUDIORESPONSE']._serialized_start=45
    _globals['_AUDIORESPONSE']._serialized_end=74
    _globals['_IMAGEFRAME']._serialized_start=76
    _globals['_IMAGEFRAME']._serialized_end=121
    _globals['_IMAGERESPONSE']._serialized_start=123
    _globals['_IMAGERESPONSE']._serialized_end=159
    _globals['_MESSAGEREQUEST']._serialized_start=161
    _globals['_MESSAGEREQUEST']._serialized_end=191
    _globals['_MESSAGERESPONSE']._serialized_start=193
    _globals['_MESSAGERESPONSE']._serialized_end=241
    _globals['_PISERVER']._serialized_start=244
    _globals['_PISERVER']._serialized_end=394
# @@protoc_insertion_point(module_scope)
